#! /bin/sh
set -e

cd $(dirname $0)

svn info |
    awk -F '[/ :]+' \
	'
		BEGIN { branch = "trunk" }
                /^Relative URL.+branches/ { branch = $5}
                /^Revision/ { revision = $2}
		END { print branch "-r" revision }
        '



